[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  TIDB_HOST = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
  TIDB_PORT = "4000"
  TIDB_USER = "xKet7a55B8AWXCZ.root"
  TIDB_PASSWORD = "wGDA8dCgw07PaR7t"
  TIDB_DATABASE = "test"
  TIDB_ENABLE_SSL = "true"
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"

[[redirects]]
  from = "/api/receipt"
  to = "/.netlify/functions/receipt"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/check-transaction"
  to = "/.netlify/functions/check-transaction"
  status = 200

[[redirects]]
  from = "/receipt"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
